# Generated by Django 5.0.12 on 2025-03-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
    ]
