GET http://127.0.0.1:8000/api/account/pending_requests/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDEyODI0LCJpYXQiOjE3NDY0MTE5MjQsImp0aSI6IjFiZDY2Y2VhM2VjZTRhNmI5M2Y0MjNkMzMxOTFjYjE0IiwidXNlcl9pZCI6Mn0.YfDFwtOMTQtHpxTIVFwjWN7NFvIW-qw0jHqGpsSl3v0

###
GET http://127.0.0.1:8000/api/account/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDEyODI0LCJpYXQiOjE3NDY0MTE5MjQsImp0aSI6IjFiZDY2Y2VhM2VjZTRhNmI5M2Y0MjNkMzMxOTFjYjE0IiwidXNlcl9pZCI6Mn0.YfDFwtOMTQtHpxTIVFwjWN7NFvIW-qw0jHqGpsSl3v0

###
POST http://127.0.0.1:8000/api/account/2/send_friend_request/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDEzMTE3LCJpYXQiOjE3NDY0MTIyMTcsImp0aSI6ImJmNTM1ZWNiMTcyMDQwYzhiNzI0YTcxYTVlMTNmZTg4IiwidXNlcl9pZCI6MX0.OZFqy6sjIfK9AM6LHdUX5qzfn7tNfdi8UdOteGw63Jc


###
POST http://127.0.0.1:8000/api/account/1/respond_friend_request/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NDEyODI0LCJpYXQiOjE3NDY0MTE5MjQsImp0aSI6IjFiZDY2Y2VhM2VjZTRhNmI5M2Y0MjNkMzMxOTFjYjE0IiwidXNlcl9pZCI6Mn0.YfDFwtOMTQtHpxTIVFwjWN7NFvIW-qw0jHqGpsSl3v0

{
  "action": "declined"
}

###
POST http://127.0.0.1:8000/api/employees/ HTTP/1.1
Content-Type:  : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDgwNDQ1LCJpYXQiOjE3NDMwODAxNDUsImp0aSI6ImM3NDhkZGYxZDdiYzRkYzZhZWI2NmQxNzAzYjMzMDhjIiwidXNlcl9pZCI6MX0.SwGwPaU2hYHyNzmb7GE21RPQ0PTf8PwHgWu1Qw-Gm20

{   
    "position": "NV",
    "name": "cuu",
    "phone_number": "0368166471",
    "email": "0cauchin0@gmail.com",
    "is_deleted": false,
    "department": 1
}