GET http://127.0.0.1:8000/api/account/pending_requests/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTM3ODY5LCJpYXQiOjE3NDY5MzY5NjksImp0aSI6IjYyMmRlNDI1NDNkMzQxMGM5MjBhNmIxNDkwNDRjMThiIiwidXNlcl9pZCI6OH0.wMVfVO4h02oK2ijPaVkK041QTkx3tlLs6Aqugn2fLFU

###
GET http://127.0.0.1:8000/api/account/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTM4NTczLCJpYXQiOjE3NDY5Mzc2NzMsImp0aSI6IjQzYjFhOWE1ZDRhOTRmNGE4MGIwMDVkYWQwZDhhYjFiIiwidXNlcl9pZCI6MX0.q2wS61yucKehsCTGSxO_JY2-3ceqgnk0nO4h76wLBWo

###
POST http://127.0.0.1:8000/api/account/2/send_friend_request/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NTM5NjMxLCJpYXQiOjE3NDY1Mzg3MzEsImp0aSI6IjU4NTQ5MTBkNzU4YzQyNjc4Y2QyNmYyZDJlMTVjZjNmIiwidXNlcl9pZCI6MX0.rwSkPJt-AZwcrkdcohPDC0bkoX3VIFvHb2oUAU457wI


###
POST http://127.0.0.1:8000/api/account/1/respond_friend_request/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NTM5ODk3LCJpYXQiOjE3NDY1Mzg5OTcsImp0aSI6ImU0OWU2ZGJmOWI4OTQ4YjJiYjU0ODAxYjBiMjk3YmM3IiwidXNlcl9pZCI6Mn0.L7-fiyoc6SdwliPTwQlb2iZYpDgO0djpLYSP_ksCRc4

{
  "action": "accepted"
}

###
###
PUT http://127.0.0.1:8000/api/account/update_profile/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NjExOTA3LCJpYXQiOjE3NDY2MTEwMDcsImp0aSI6Ijk0YzE3ZWE5ODNkZDRiNTFhNWVlYjEyZGMxNDJiODhhIiwidXNlcl9pZCI6M30.zdA3zMeOCnRvBmEzvgGvvHxySVkj4wS38UUSYnS6jhs

{
    "full_name": "Cuu",
    "sex": "Nam",
    "birthday": "2025-08-05"
}