# Generated by Django 5.0.12 on 2025-03-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('audio_url', models.CharField(max_length=255, verbose_name='Đường dẫn')),
                ('duration', models.CharField(max_length=255, verbose_name='Thời gian kết thúc')),
                ('lyrics', models.CharField(max_length=1000, verbose_name='Lời bài hát')),
                ('name', models.CharField(max_length=255, verbose_name='Tên bài hát')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='album.album', verbose_name='Album')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_songs', to='video.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'db_table': 'songs',
            },
        ),
    ]
