# Generated by Django 5.0.12 on 2025-03-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('song', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='album.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_songs', to='video.video', verbose_name='Video'),
        ),
    ]
