# Generated by Django 5.0.12 on 2025-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_album_alter_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(verbose_name='Thời lượng (giây)'),
        ),
    ]
