# Generated by Django 5.0.12 on 2025-04-14 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_name'),
        ('song', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='artist.artist', verbose_name='Nghệ sĩ'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thể loại'),
        ),
    ]
