# Generated by Django 5.0.12 on 2025-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_alter_song_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời lượng (giây)'),
        ),
    ]
