# Generated by Django 5.0.12 on 2025-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_remove_song_artist_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lời bài hát'),
        ),
    ]
