# Generated by Django 5.0.12 on 2025-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_alter_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='songs/imgs', verbose_name='Ảnh bìa'),
        ),
    ]
