# Generated by Django 5.0.12 on 2025-05-05 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_img_url'),
        ('favourite_album', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritealbum',
            constraint=models.UniqueConstraint(fields=('account', 'album'), name='unique_account_album_favourite'),
        ),
    ]
