# Generated by Django 5.0.12 on 2025-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.FileField(upload_to='albums/', verbose_name='Ảnh bìa'),
        ),
    ]
