# Generated by Django 5.0.12 on 2025-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='albums/', verbose_name='Ảnh bìa'),
        ),
    ]
