# Generated by Django 5.0.12 on 2025-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên album')),
                ('img_url', models.CharField(max_length=255, verbose_name='Đường dẫn')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'db_table': 'artists',
            },
        ),
    ]
