# Generated by Django 5.0.12 on 2025-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_deleted',
            field=models.FileField(blank=True, null=True, upload_to='artists/', verbose_name='Ảnh bìa'),
        ),
    ]
