# Generated by Django 5.0.12 on 2025-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='artists/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
    ]
