# Generated by Django 5.0.12 on 2025-03-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_alter_artist_name'),
        ('song', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_singers', to='artist.artist', verbose_name='artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_singers', to='song.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'singer',
                'verbose_name_plural': 'singers',
                'db_table': 'singers',
            },
        ),
    ]
