# Generated by Django 5.0.12 on 2025-04-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=255, verbose_name='Tiêu đề video'),
            preserve_default=False,
        ),
    ]
