# Generated by Django 5.0.12 on 2025-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='videos/', verbose_name='File video'),
        ),
    ]
