# Generated by Django 5.0.12 on 2025-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời lượng (giây)'),
        ),
    ]
