# Generated by Django 5.0.12 on 2025-05-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0008_song_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_favourite_songs', to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_songs', to='song.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'favourite_song',
                'verbose_name_plural': 'favourite_songs',
                'db_table': 'favourite_songs',
            },
        ),
    ]
