# Generated by Django 5.0.12 on 2025-05-05 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_song', '0001_initial'),
        ('song', '0008_song_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritesong',
            constraint=models.UniqueConstraint(fields=('account', 'song'), name='unique_account_song_favourite'),
        ),
    ]
