# Generated by Django 5.0.12 on 2025-05-04 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên album')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Mô tả')),
                ('img_url', models.FileField(blank=True, null=True, upload_to='album_users/', verbose_name='Ảnh bìa')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_albums', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'album_user',
                'verbose_name_plural': 'album_users',
                'db_table': 'album_users',
            },
        ),
    ]
